import Fold from './Fold'
import Plus from './Plus'
import Home from './Home'
import Done from './Done'
import InBox from './InBox'
import WorkSpace from './WorkSpace'
import Triangle from './Triangle'
import More from './More'
import Box from './Box'
import Arrow from './Arrow'
import Right from './Right'
import Avatar from './Avatar'
import TinyPlus from './TinyPlus'
import List from './List'
import Lock from './Lock'
import Completed from './Completed'
import Calendar from './Calendar'
import Clock from './Clock'
import Repeat from './Repeat'
import Eye from './Eye'
import Trash from './Trash'
import Apps from './Apps'
import Close from './Close'

export {Close, Apps, Trash, Eye, Fold,Plus,Home,Done,InBox,WorkSpace,Triangle,More,Box,Arrow,Right,Avatar,TinyPlus,List,Lock,Completed,Calendar,Clock, Repeat}